### ISSUE TITLE
Amazon's internal link in a comment

### ISSUE THREAD

**Issue by kirillDanshin** [firecracker-microvm/firecracker-demo#16]
https://github.com/firecracker-microvm/firecracker-demo/blob/master/start-firecracker.sh#L6

<img width="880" alt="" src="https://user-images.githubusercontent.com/9026581/62586568-cd5d7400-b8c6-11e9-9da3-299d225cce6b.png">

**Comment by dianpopa** [comment]
@kirillDanshin thanks for reporting this!
