### ISSUE TITLE
extract-times.sh does not work due to logger mis-configuration

### ISSUE THREAD

**Issue by dizz** [firecracker-microvm/firecracker-demo#19]
Issue #, if available: n/a

*Description of changes:*

* update to logger API request to fix boot time calculation

Hi,
When running the benchmark, the statistics generated by `extract-times.sh` cannot work as the information searched for is presented as an "Info" message and not "Warn" as in the script. You can [see here what the necessary change](https://gist.github.com/dizz/4b272423be823515a51cecb949b911e6#file-start-firecracker-sh-L72) is.

HTH,
Andy

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

**Comment by acatangiu** [comment]
@dizz would you be interested to open a pull request to update this?

**Comment by dianpopa** [comment]
Fixed by #20.
