### ISSUE TITLE
Permissions denied for limits.conf

### ISSUE THREAD

**Issue by arun-gupta** [firecracker-microvm/firecracker-demo#2]
The following command on Ubuntu 18.04 on `i3.metal` instance:

```
sudo cat >> /etc/security/limits.conf <<EOL
ubuntu soft nproc 16384
ubuntu hard nproc 16384
EOL
```

is giving the following error:

```
-bash: /etc/security/limits.conf: Permission denied
```

Editing the file manually using `sudo vim` works

**Comment by samuelkarp** [comment]
Try this:

```bash
sudo tee -a /etc/security/limits.conf <<EOL
ubuntu soft nproc 16384
ubuntu hard nproc 16384
EOL
```

You're getting a failure because `bash` is the process attempting to write the file instead of `cat`, and `bash` is not running under `sudo`.

**Comment by arun-gupta** [comment]
Yep, that worked. Had that same issue in AL2 as well.

**Comment by arun-gupta** [comment]
The command in the docs need to be updated, and so reopening the issue.

**Comment by kzys** [comment]
@MitchyBAwesome updated the section in April. We can close the issue now.
