### ISSUE TITLE
ssh connection refused on port 22

### ISSUE THREAD

**Issue by subash1** [firecracker-microvm/firecracker-demo#27]
I am building custom rootfs image from the scratch, 

when i use demo image, ssh working fine. but mine is not working
i have installed openrc, util-linux, openssh packages. 
added in the rc-update add sshd default.
also copied the authorization keys too.

i am passing guest ip in the boot args.

when i saw inside the demo image, i seen /etc/init.d/sshd.eth0. 
is that think i missed?

**Comment by iulianbarbu** [comment]
Hello, @subash1,

Can you be a little bit more specific about your problem?
What do you try to accomplish?

**Comment by subash1** [comment]
@iulianbarbu , i am starting multiple micro vm as per instruction in demo.
i can ping the vm ip, its working fine. lets say 169.254.0.5.
but when when in ssh its not wroking it saying connection refused.
if i use demo rootfs, it working, i can ssh into it.
but i build a rootfs as per the firecracker docs. 
i just installed 
`apk add openssh;
rc-update add sshd default`

and copy the authorization_keys in /root/.ssh

**Comment by andreeaflorescu** [comment]
@subash1 can you run the ssh with debug information and paste the output of the command:
```ssh -vvv root@169.254.0.5```

**Comment by acatangiu** [comment]
@subash1 please see https://wiki.alpinelinux.org/wiki/Setting_up_a_ssh-server for a guide on how to set up a ssh server on Alpine Linux.

Also make sure you set a default route in the guest through (one of) the configured interfaces.

See https://wiki.alpinelinux.org/wiki/Configure_Networking#Ethernet_Configuration or [this](https://unix.stackexchange.com/questions/486834/how-to-persist-iproute2-routes-and-rules-in-alpine-linux).

Also, like @andreeaflorescu said, `-vvv` will show a lot more detail on why it's failing for you.

**Comment by subash1** [comment]
this is the output of `ssh -vvv root@169.254.0.5`

> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\n
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "169.254.0.5" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 169.254.0.5 [169.254.0.5] port 22.
debug1: connect to address 169.254.0.5 port 22: Connection refused
ssh: connect to host 169.254.0.5 port 22: Connection refused

in rootfs.ext4 added `etc/network/interfaces` .
and here is the content of that

> auto eth0
iface eth0 inet manual


also did `rc-update add networking default`

**Comment by iulianbarbu** [comment]
@subash1 ,

Setting up applications inside the custom rootfs is not in the scope of the current firecracker-demo, so this discussion should be moved to Firecracker slack channel, and maybe someone from the community can help you with the configuration of ssh.
