### ISSUE TITLE
Script missing

### ISSUE THREAD

**Issue by nbrandaleone** [firecracker-microvm/firecracker-demo#31]
In the 0.inital-setup.sh setup script, it refers to another script on line 14. This new script "./setup-network-taps.sh" does not exist in the directory.

**Comment by alannair** [comment]
It is present in the `scripts` directory. In the `0.initial-setup.sh` script, the `scripts` directory is pushed onto the current directory stack via `pushd` before executing the `setup-network-taps.sh` script.

**Comment by dianpopa** [comment]
Hi,

Thanks @alannair for the clarifications. @nbrandaleone Indeed the "setup-network-taps.sh" is located in the [scripts](https://github.com/firecracker-microvm/firecracker-demo/tree/main/scripts) directory.

Feel free to re-open in case you need any further guidance.
