### ISSUE TITLE
Heatmap not working. 

### ISSUE THREAD

**Issue by ashishxooa** [firecracker-microvm/firecracker-demo#5]
Hi, my microvms are launched and working. But the heatmap is not working, would have been cool to see them. 

I 'm using a i3.metal with ubuntu-18.04, 

ubuntu@ip-172-31-85-171:~/firecracker-demo$ python3 microvm-tiles.py
Traceback (most recent call last):
  File "microvm-tiles.py", line 99, in <module>
    curses.wrapper(render_microvms)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "microvm-tiles.py", line 35, in render_microvms
    curses.init_color(shade, 200 + shade * 8, 200 + int(shade * 4.8), 208)
_curses.error: init_color() returned ERR

Regards,
Ashish

**Comment by qubitrenegade** [comment]
Can confirm, running `export TERM='xterm-256color'` fixed it for me.
