### ISSUE TITLE
Failed to run ./parallel-start-many.sh 0 4000 6

### ISSUE THREAD

**Issue by SherryjZhu** [firecracker-microvm/firecracker-demo#6]
While running ./parallel-start-many.sh 0 4000 6 on ec2 i3.metal, we kept getting following errors.

touch: cannot touch '/home/ubuntu/firecracker-demo/firecracker-demo/output/fc-sb3961-log'touch: cannot touch '/home/ubuntu/firecracker-demo/firecracker-demo/output/fc-sb1961-log': Permission denied
: Permission denied
touch: cannot touch '/home/ubuntu/firecracker-demo/firecracker-demo/output/fc-sb1293-log': Permission denied

Seems like it failed to run 4000 vms but heatmap shows they are all active. Also is there a quick way to stop them?

**Comment by acatangiu** [comment]
@SherryjZhu so sorry for the very late response. Those errors are probably being reported because you've run the demo with `sudo` which created the `output` directory and subsequent non-`sudo` runs cannot access it.

> Also is there a quick way to stop them?

Run `sudo ./9.cleanup.sh`, or simply `sudo killall firecracker`.

**Comment by acatangiu** [comment]
Feel free to reopen if needed.
