### ISSUE TITLE
What is the root password for the demo. I cant login to microvm after loading it.

### ISSUE THREAD

**Issue by petermp79** [firecracker-microvm/firecracker-demo#8]
~/firecracker-demo$ ssh -i xenial.rootfs.id_rsa root@169.254.0.2
The authenticity of host '169.254.0.2 (169.254.0.2)' can't be established.
ECDSA key fingerprint is SHA256:6hwt5lKQbNMbiPbcuCjwWfwcMS4QrGmspQyyzlYoNsA.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '169.254.0.2' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0664 for 'xenial.rootfs.id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "xenial.rootfs.id_rsa": bad permissions
root@169.254.0.2's password: 
Permission denied, please try again.
root@169.254.0.2's password: 
Permission denied, please try again.
root@169.254.0.2's password: 
Permission denied (publickey,password).

**Comment by petermp79** [comment]
Thank, Alex. You are head on. I was not aware of the ip address assignment scheme.

**Comment by alexandruag** [comment]
Nice to hear things work now! Closing this.
